version: "2"
services:
  radotp:
   image: ghcr.io/abbas-gheydi/radotp:main
   restart: always
   ports:
    - "80:8080"
    - "443:8081"
    - "1812:1812/udp"
   volumes:
   - ./config/:/etc/radotp/
   depends_on:
   - db
   - prometheus
   
  prometheus:
   image: prom/prometheus:v2.47.0
   restart: always
   volumes:
   - prom_data:/prometheus-data
   - type: bind
     source: prometheus.yml
     target: /etc/prometheus/prometheus.yml

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=radotp
      - POSTGRES_PASSWORD=radotp
      - POSTGRES_DB=radotp
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  prom_data:
